version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "00:00"
    timezone: America/Chicago
  ignore:
    - dependency-name: "*"
      update-types: ["version-update:semver-patch"]
  open-pull-requests-limit: 5
